### ISSUE TITLE
windmap is never used.

### ISSUE THREAD

**Issue by miguelmyers8** [weigert/SimpleWindErosion#1]
I'm trying to re-engineer your code. I ran into a roadblock, it seems that windmap array is never used. You have it as input to `wind.fly` function but it never gets updated.

**Comment by weigert** [comment]
Hi,

Thanks for your interest in reimplementing my code.

If you read the function `void World::erode(int cycles)`, you will notice that it works in three steps:
1. Define a boolean tracking map
2. Fly for a number of cycles (passing the tracking map an wind-map)
3. Update the wind-map using the tracking map.

The tracking map is a boolean map, which is then converted to the wind-map using a rolling average. This is done so that every simulated wind-particle for a set of cycles uses the same "input" wind-map. Only the tracking map is updated. Then, when all cycles are completed, we update the wind-map.

If I updated the wind-map in the `wind.fly` function, then every particle for a set of cycles would have a different input map.

Because the paths of particles can be sparse compared to the size of the map, it makes the most sense mathematically to "AND" them together this way instead of using a direct average. You could consider this a kind of buffer ping-ponging using a rolling average (parameter `lrate` is "learning rate").

You can think about this as: **Two sets of combined paths of N random particles can be better characteristically compared than two sets of paths of 1 random particle.**

Of course this is a heuristic, and if you were to assign the wind-map a more precise physical meaning other than a time-averaged relative population density, you could define a better update formula.

Hope this helps.

**Comment by miguelmyers8** [comment]
ok, I see. Thanks for the clarification. I'm trying to reimplement this in Js.
